### PR TITLE
feat: Minimal format

### PR DESCRIPTION
**Pull request by roberth**
When including documentation into a dedicated page, we have different needs.

- Add `--anchor-prefix` to avoid unnecessary/inaccurate `function-library-` prefix.

- Don't render a header when description and category are empty. These can be handled by the parent document when using an "include" feature of a markdown processor / site generator.

- Add this usage to the README. Good to help non-Nixpkgs users and let nixdoc grow outside of that context.

Also tested with #139

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
Other than the need for a changelog entry, this looks good to me!

**Comment by GrahamDennis** [comment]
@infinisil Is it possible to cut a release with this fix so nixdoc can be updated in nixpkgs?

**Comment by infinisil** [comment]
@GrahamDennis [Yup, here you go](https://github.com/nix-community/nixdoc/releases/tag/v3.1.0) :slightly_smiling_face:

**Comment by GrahamDennis** [comment]
Thanks!

**Pull request merged**
