### PR TITLE
Flake:init

### PR DESCRIPTION
**Pull request by asymmetric**
- adds a `flake.nix`
- converts `default.nix` to load `flake.lock`
- adds `direnv` support

### CODE REVIEW

**Review by ryantm — APPROVED** [review]
I don't like flake-utils, but sure okay.

**Comment by LoveIsGrief** [comment]
Will it be possible to use the project without activating flake support? Or is it activated by default and a stable feature now?

**Comment by ryantm** [comment]
@LoveIsGrief this project is available in Nixpkgs, so it should remain available for use without Flakes. The stability of flakes is a subject you should ask the Nix maintainers, not us.

**Comment by asymmetric** [comment]
@LoveIsGrief non-flakes is still fully supported, via [`flake-compat`](https://github.com/edolstra/flake-compat), meaning you can keep on using this through `default.nix` as before.

**Pull request merged**
