### PR TITLE
Allow empty prefix

### LINKED ISSUE #119: Support empty prefix
I'm trying to write a `pkgs.moduleSystem` library (for the option docs generating part, replacing `nixosOptionsDoc`), but passing that as a prefix results in rather long titles.
I figured `--prefix ""` would do the right thing, but that still generates a "separator", resulting in headers like `.rendering`, which isn't quite right.
The default prefix is `lib`, not an internal representation for "no prefix at all", unfortunately.

I propose that `--prefix ""` will be the accepted syntax for prefixing nothing at all; not even the separating `.`.

Context:
- https://github.com/NixOS/nixpkgs/pull/305847

### PR DESCRIPTION
**Pull request by hsjobeki**
Requires #121 to be merged first.

This closes #119 

empty prefix or catgeory is possible when this gets merged

### CODE REVIEW

**Comment by hsjobeki** [comment]
@infinisil should we merge this ?

**Review by infinisil — COMMENTED** [review]
Hmm I don't like how this breaks rendering when the flag is specified. How about just making it so that the `.` is only added if the prefix is non-empty?

**Comment by hsjobeki** [comment]
> Hmm I don't like how this breaks rendering when the flag is specified. How about just making it so that the `.` is only added if the prefix is non-empty?

Just pushed a new commit, to simply allow empty prefixes. 

Maybe a future pr could make the seperator configurable

**Comment by hsjobeki** [comment]
@infinisil any open points? Otherwise could we merge this.

**Review by infinisil — APPROVED** [review]
Looking good, sorry for the delay!

Could you do the release yourself? Note that I usually manually edit the changelog in the release to match previous releases, though in the future I'd hope to get more automation for this (see https://github.com/NixOS/nixpkgs-check-by-name/pull/46)

**Pull request merged**
